# Generated by Django 4.1.5 on 2023-08-08 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('can_edit_authors', 'Set author as edited'),)},
        ),
    ]
