# Generated by Django 4.1.5 on 2023-08-08 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name'], 'permissions': (('can_edit_authors', 'Set author as edited'),)},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
    ]
